server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/phone_store?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
